server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="ewk3pk5f" password="YYOpwGUHkcEBC-wRUOfblNdIdwBp20gh";
  cloud:
#    function:
#      definition: output;nttdata
    stream:
      bindings:
        nttdata-out-0:
          destination: ewk3pk5f-nttdata
  application:
    name: bootcoin-service
  data:
    mongodb:
      database: Bootcoindb
      host: localhost
      port: 27017